num_image_channels: 3

generator:
  num_features: 64
  latent_vector: 100

discriminator:
  num_features: 64

train:
  dataset_path: './celeb' # relative path from datasets directory to root of dataset
  batch_size: 128
  learning_rate: 0.0002
  beta1: 0.5
  epochs: 5
  workers: 2
  device: 'cuda:0'
  ngpu: 1 # number of gpus to use

  smooth_alpha: 0.1 # one side true label smoothing. 0 to disable label smoothing
