type: DCGan

network:
  num_image_channels: 3

  discriminator:
    num_features: 64

  generator:
    num_features: 64
    latent_vector: 100

train:
  dataset_path: './celeb' # relative path from datasets directory to root of dataset
  batch_size: 128
  optimizer:
    lr: 0.0002
    betas: [0.5,0.999]
  epochs: 10
  dis_iter: 1 # number of iterations optimizing discriminator (min=1)
  workers: 2
  device: 'cuda:0'
  ngpu: 1 # number of gpus to use

  smooth_alpha: 0.1 # one side true label smoothing. 0 to disable label smoothing
