type: Wgan_GP

network:
  num_image_channels: 3

  discriminator:
    num_features: 64

  generator:
    num_features: 64
    latent_vector: 100

train:
  dataset_path: './celeb' # relative path from datasets directory to root of dataset
  batch_size: 64
  optimizer:
    lr: 0.0002
    betas: [0.5, 0.999]
  epochs: 5
  dis_iter: 5 # number of iterations optimizing discriminator (min=1)
  workers: 2
  device: 'cuda:0'
  ngpu: 1 # number of gpus to use

  reg_weight: 10 # one side true label smoothing. 0 to disable label smoothing
